language: php

env:
  global:
    - PHPCS=0
    - RUN_TESTS=1

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - sh -c "if [ '$RUN_TESTS' = '1' ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p -n --extensions=php --standard=psr2 ./src ./tests; fi"

notifications:
  email: false
